language: elixir
elixir:
  - 1.3.0
  - 1.4.0
  - 1.5.0
otp_release:
  - 18.0
  - 19.0
  - 20.0
script:
  - mix test

matrix:
  exclude:
    - elixir: 1.3.0
      otp_release: 20.0
    - elixir: 1.4.0
      otp_release: 20.0
